id: A33AEB6BE
base_file: f9828.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-17 12:21:23.600992
  last_modified_at: 2022-06-17 12:21:23.600999
